config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  resources :members do
    match "search" => 'members/search#index', as: 'search', via: [:get, :post]
  end
  resources :friendships, only: [:new, :create, :destroy]
  match "/" => 'search#index', as: 'search', via: [:get, :post]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root "search#index"

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friendship.rb
# frozen_string_literal: true

class Friendship < ApplicationRecord
  belongs_to :member
  belongs_to :friend, class_name: 'Member'

  validates :member_id, uniqueness: { scope: :friend_id }
  validate :not_self

  after_create :create_inverse, unless: :inverse?
  after_destroy :destroy_inverse, if: :inverse?

  def inverse
    self.class.find_by(inverse_friendship_options)
  end

  private

  def not_self
    errors.add(:friend, "can't be equal to member") if member == friend
  end

  def create_inverse
    self.class.create(inverse_friendship_options)
  end

  def destroy_inverse
    inverse.destroy
  end

  def inverse?
    self.class.exists?(inverse_friendship_options)
  end

  def inverse_friendship_options
    { friend_id: member_id, member_id: friend_id }
  end
end

app/models/headline.rb
# frozen_string_literal: true

class Headline < ApplicationRecord
  belongs_to :member

  validates :content, :level, presence: true

  def self.search_by_content(content)
    where('content ILIKE ?', "%#{content}%")
  end
end

app/models/member.rb
# frozen_string_literal: true

class Member < ApplicationRecord
  validates :name, presence: true
  validates :website_url, presence: true, url: true

  has_many :headlines, dependent: :destroy
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  def shortest_connection_to(other_member) # rubocop:disable Metrics/MethodLength
    # Breadth-first search to find the shortest connection between two members
    return [self] if self == other_member

    visited = {}
    queue = [[self]]

    while queue.any?
      path = queue.shift
      current_member = path.last

      next unless visited[current_member.id].nil?

      visited[current_member.id] = true

      current_member.friends.each do |friend|
        new_path = path + [friend]
        return new_path if friend == other_member

        queue << new_path
      end
    end

    [] # No connection found
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/friendships_controller.rb
# frozen_string_literal: true

class FriendshipsController < ApplicationController
  def new
    @friendship = Friendship.new(member_id: params[:member_id], friend_id: params[:friend_id])
    @members = Member.all
  end

  def create
    @friendship = Friendship.new(friendship_params)

    if @friendship.save
      redirect_to members_path
    else
      @members = Member.all
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @friendship = Friendship.find(params[:id])

    if @friendship.destroy
      flash[:notice] = 'Friendship removed.'
    else
      flash[:alert] = 'Unable to remove friendship.'
    end
    redirect_back(fallback_location: members_path)
  end

  private

  def friendship_params
    params.require(:friendship).permit(:member_id, :friend_id)
  end
end

app/controllers/members/search_controller.rb
# frozen_string_literal: true

module Members
  class SearchController < ApplicationController
    before_action :set_member

    def index
      return if params[:search].blank?

      @headlines = Headline.includes(:member).search_by_content(params[:search])
                           .where.not(member_id: @member.id)
      preload_shortest_connections
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:member_id])
    end

    def preload_shortest_connections
      @shortest_connections = {}
      @headlines.each do |headline|
        next if @shortest_connections[headline.member_id].present?

        @shortest_connections[headline.member_id] =
          @member.shortest_connection_to(headline.member).map(&:name).join(' -> ')
      end
    end
  end
end

app/controllers/members_controller.rb
# frozen_string_literal: true

class MembersController < ApplicationController
  before_action :set_member, only: %i[show edit update destroy]

  # GET /members
  def index
    @members = Member.all
    @member_headlines_count = @members.joins(:headlines).group('headlines.member_id').count
  end

  # GET /members/1
  def show; end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit; end

  # POST /members
  def create
    @member = Member.new(member_params)

    if @member.save
      CollectHeadlinesJob.perform_later(@member.id)
      redirect_to @member, notice: 'Member was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /members/1
  def update
    if @member.update(member_params)
      redirect_to @member, notice: 'Member was successfully updated.', status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /members/1
  def destroy
    @member.destroy!
    redirect_to members_url, notice: 'Member was successfully destroyed.', status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_member
    @member = Member.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def member_params
    params.require(:member).permit(:name, :website_url)
  end
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  def index
    return if params[:search].blank?

    @headlines = Headline.includes(:member).search_by_content(params[:search]).limit(50)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/friendships/new.html.erb
<h1>Create New Friendship</h1>

<%= form_with(model: @friendship) do |form| %>
  <% if @friendship.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this Friendship from being saved:</h2>

      <ul>
        <% @friendship.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :member_id, "Select Member", style: "display: block" %>
    <%= form.select :member_id, options_from_collection_for_select(@members, :id, :name, @friendship.member_id),include_blank: true %>
  </div>
  <div>
    <%= form.label :friend_id, "Select Friend", style: "display: block" %>
    <%= form.select :friend_id, options_from_collection_for_select(@members, :id, :name, @friendship.friend_id), include_blank: true  %>
  </div>
  <div>
    <%= form.submit "Create Friendship" %>
  </div>
<% end %>

<%= link_to 'Back', :back %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HeadlineNetwork</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script async src="https://ga.jspm.io/npm:es-module-shims@1.8.2/dist/es-module-shims.js" data-turbo-track="reload"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member) do |form| %>
  <% if member.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :website_url, style: "display: block" %>
    <%= form.text_field :website_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/members/_member.html.erb
<div id="<%= dom_id member %>">
  <p>
    <strong>Name:</strong>
    <%= member.name %>
  </p>

  <p>
    <strong>Website Url:</strong>
    <%= member.website_url %>
  </p>

  <p>
    <strong>Website Headlines(<%= member.headlines.count%>):</strong>
    <ul>
      <% member.headlines.each do |headline| %>
        <li><%= headline.content %> (<%= headline.level%>)
      <%end%>
    </ul>
  </p>

  <p>
    <strong>Friends(<%= member.friendships.count%>):</strong>
    <ul>
      <% member.friendships.each do |friendship| %>
        <li><%= link_to friendship.friend.name, friendship.friend %> (<%= link_to "Remove Friend", friendship_path(friendship), data: {turbo_method: :delete, turbo_confirm: "Are you sure?" } %>)</li>
      <%end%>
    </ul>
  </p>

  <p>
    <strong>Headline Friendship search</strong>
    <%= render partial: "members/search/form", locals: {member: member}%>
  </p>
</div>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render "form", member: @member %>

<br>

<div>
  <%= link_to "Show this member", @member %> |
  <%= link_to "Back to members", members_path %>
</div>

app/views/members/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Website Url</th>
      <th>Website Headlines Count</th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= link_to member.name, member%></td>
        <td><%= member.website_url %></td>
        <td><%= @member_headlines_count[member.id] %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to "Headline Search", search_path %> |
<%= link_to "New member", new_member_path %> |
<%= link_to "New friendship", new_friendship_path %>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render "form", member: @member %>

<br>

<div>
  <%= link_to "Back to members", members_path %>
</div>

app/views/members/search/_form.html.erb
<%= form_with url: member_search_path(member), data: {turbo: false} do %>
  <%= label_tag :search, "Search for:" %>
  <%= search_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end%>

app/views/members/search/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Headline friends search from <%= @member.name %></h1>

<%= render partial: 'form', locals:{member: @member}%>

<% if params[:search].present? %>
  <h2>Results for "<%= params[:search]%>"</h2>
  <% if @headlines.present? %>
    <table>
      <thead>
        <tr>
          <th>Headline </th>
          <th>Member</th>
          <th>Shortest Connection</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @headlines.each do |headline|  %>
          <tr>
            <td><%= headline.content %></td>
            <td><%= link_to headline.member.name, headline.member %></td>
            <td><%= @shortest_connections[headline.member_id] %></td>
            <td>
              <% unless Friendship.exists?({member_id: @member.id, friend_id: headline.member}) %>
                <%= link_to "Befriend", new_friendship_path(member_id: @member.id, friend_id: headline.member) %>
              <% end  %></td>
          </tr>
        <% end%>
      </tbody>
    </table>
  <% else %>
    <p>No headlines found!</p>
  <% end%>
<% end%>


<%= link_to "Back to member", @member %>

app/views/members/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @member %>

<div>
  <%= link_to "Edit this member", edit_member_path(@member) %> |
  <%= link_to "Add Friendship with member", new_friendship_path(member_id: @member.id) %> |
  <%= link_to "Back to members", members_path %>
</div>
<div>
  <%= button_to "Destroy this member", @member, method: :delete, form: {data: {turbo_confirm: "Are you sure?" }}  %>
</div>

app/views/search/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Headline search</h1><p style="color: green"><%= notice %></p>

<%= form_with url: search_path, data: {turbo: false} do %>
  <%= label_tag :search, "Search for:" %>
  <%= search_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end%>

<% if params[:search].present? %>
  <h2>Results for "<%= params[:search]%>"</h2>
  <% if @headlines.present? %>
    <table>
      <thead>
        <tr>
          <th>Headline </th>
          <th>Member</th>
        </tr>
      </thead>
      <tbody>
        <% @headlines.each do |headline|  %>
          <tr>
            <td><%= headline.content %></td>
            <td><%= link_to headline.member.name, headline.member%></td>

          </tr>
        <% end%>
      </tbody>
    </table>
  <% else %>
    <p>No headlines found!</p>
  <% end%>
<% end%>


<%= link_to "All Members", members_path %>